- name: Deploy myapp to Kubernetes
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply Deployment
      k8s:
        state: present
        definition: |
          {{ lookup('file', 'myapp-deployment.yaml')}}
      register: deployment_result
    
    - name: Apply Service
      k8s:
        state: present
        definition: |
          {{ lookup('file', 'myapp-loadbalancer-service.yaml')}}
      register: service_result

    - name: Display Deployment Result
      debug:
        var: deployment_result

    - name: Display Service Result
      debug:
        var: Sevice_result